---
# tasks file for postgres

- name: install postgres
  yum:
    name: postgresql-server
    state: latest

# only run the next 2 tasks once!
- name: initilize postgres
  command: postgresql-setup initdb
  args:
    creates: /var/lib/pgsql/data/postgresql.conf
    warn: false

- name: start postgres
  service:
    name: postgresql
    enabled: yes
    state: started
